info:
  description: Spring Cloud Samples
  version: 
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
  
eureka:
  hostname: localhost
  password: s3cr3t
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password:}@localhost:8761/eureka/
 