info:
  description: Sample Application
  version: 
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    enabled: true
    sensitive: false

####################
# PROFILE unittest #
####################
spring:
  profiles: unittest
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    pooledDsFactory: org.leaf.db.ds.PooledDataSourceFactory
    avg: 2
    max: 8
    min: 1
test:
  props1: TEST PROPEPERTY FROM CLOUD - PROFILE UNITTEST

####################
# PROFILE test     #
####################
---
spring:
  profiles: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    pooledDsFactory: org.leaf.db.ds.PooledDataSourceFactory
    avg: 2
    max: 8
    min: 1
test:
  props1: TEST PROPEPERTY FROM CLOUD - PROFILE TEST

####################
# PROFILE dev      #
####################
---
spring:
  profiles: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    pooledDsFactory: org.leaf.db.ds.PooledDataSourceFactory
    avg: 2
    max: 8
    min: 1
test:
  props1: TEST PROPEPERTY FROM CLOUD - DEV
