####################
# PROFILE LOCAL    #
####################
spring:
 profiles: local
 redis:
  host: 127.0.0.1
  port: 6379
datasources:
 primary:
  dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
  jdbcUrl: jdbc:mysql://localhost:3306/sample
  username: root
  password: root
  maximumPoolSize: 5
test:
  props1: TEST PROPEPERTY FROM CLOUD - PROFILE LOCAL