spring:
  profiles: unittest
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    pooledDsFactory: org.leaf.db.ds.PooledDataSourceFactory
    avg: 2
    max: 8
    min: 1
test:
  props1: TEST PROPEPERTY FROM CLOUD - PROFILE UNITTEST
---
spring:
  profiles: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    pooledDsFactory: org.leaf.db.ds.PooledDataSourceFactory
    avg: 2
    max: 8
    min: 1
test:
  props1: TEST PROPEPERTY FROM CLOUD - PROFILE TEST
---
spring:
  profiles: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    pooledDsFactory: org.leaf.db.ds.PooledDataSourceFactory
    avg: 2
    max: 8
    min: 1
test:
  props1: TEST PROPEPERTY FROM CLOUD - DEV
