####################
# PROFILE LOCAL    #
####################
spring:
 profiles: local
 redis:
  host: 127.0.0.1
  port: 6379
datasources:
 primary:
  driverClassName: org.h2.Driver
  jdbcUrl: jdbc:mysql://localhost/sample
  username: root
  password: root
  maximumPoolSize: 5
test:
  props1: TEST PROPEPERTY FROM CLOUD - PROFILE LOCAL